# Generated by Django 5.1.7 on 2026-09-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_user_name_booking_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='idempotency_key',
            field=models.UUIDField(unique=True),
        ),
    ]
