# Generated by Django 5.1.7 on 2026-09-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_idempotency_key'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='room',
            name='available_slots_lte_capacity',
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('available_slots__gte', 0), ('available_slots__lte', models.F('capacity'))), name='available_slots_lte_capacity'),
        ),
    ]
